# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5b475faaee24ffec1a61145b0397544699e1d5721040b2e92a7834a5eae49656a1f8fbc32960fe446c36811f8db457b5096a458c4a60af3828c53a93426b4f82

test:
  secret_key_base: 94369151b9dc3b9be872583f8cb064d228dac2bfb9b27d6f258d92418fa148fab4319dd65d1dde682486e40482e5c21501cc8bfffc387f1ee75b6e5b07a8d8f4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
